name: Publish

on:
  push:
    tags: [v*]

env:
  NODE_VERSION: 18

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://npm.im/express-html-minifier-terser

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - run: node --version
      - run: npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}